### ISSUE TITLE
Approval to Publish: Using your own smartphone, laptop, tablet or PC for work

### ISSUE THREAD

**Issue by tomdMOJ** [ministryofjustice/itpolicycontent#17]
Hi Jon,

Using your own smartphone, laptop, tablet or PC for work guide is ready for publishing. Jennifer reviewed the document and is happy for it to be published, so I'm requesting a final OK from you.

You can see the final draft here:

https://ministryofjustice.github.io/itpolicycontent/content/using-your-own-smartphone-laptop-tablet-or-pc-for-work.html

Thanks,

Tom

**Comment by cybersquirrel** [comment]
Hello,

Some questions - hopefully simple!
- style: do we have a house-style for MoJ v MOJ? 
- the 'contact the service desk' question at the end - is this something that Service Desk are prepared for?
- the 'services you can use' section feels like it's mixing two different things together - the set of services which we're ok with people using on their own devices (again, is the O365 set-up ready for this?), and information on which services are approved for different types of data (e.g. you can't put SENSITIVE data into slack). I think the latter should be the Open Internet Tools guidance that @warmana is working on, and should just be linked to from here, rather than repeated, if that makes sense?

Thanks,

Jon.

**Comment by tomdMOJ** [comment]
Hi Jon,

Quick answers:

- style:  do we have a house-style for MoJ v MOJ?
We use MOJ as defined by the GOV.UK Style Guide

- the  'contact the service desk' question at the end - is this something that Service Desk are prepared for?

Something I can't confirm at this stage, but this line was in the original document I inherited. Needs checking, as well as providing the Service Desk with some guidelines.

- the  'services you can use' section feels like it's mixing two different things together - the set of services which we're ok with people using on their own devices (again, is the O365 set-up ready for this?), and information on which services are approved for different types of data (e.g. you can't put SENSITIVE data into slack). I think the latter should be the Open Internet Tools guidance that @warmana is working on, and should just be linked to from here, rather than repeated, if that makes sense?

Speaking to Adrian, the Open Internet Tools guidance wont be ready for publishing for another few weeks. Unless you feel the information as currently written is not right/confusing, we can publish and then make the necessary edits and links once the Open Internet Tools guidance is published.

Let me know your thoughts.

Tom

**Comment by cybersquirrel** [comment]
Thanks Tom - appreciate swift response.

- Style: happy with this (and helps me stay consistent!)
- Contact service desk: Please can we check on this before we publish.
- Services you can use: I think that this section is potentially confusing, as I would expect a fairly simple list of services here (possibly with constraints or usage restrictions). As it stands, this is a section on 'which services can I use with sensitive data', and doesn't answer the headline question...

Jon.

**Comment by tomdMOJ** [comment]
Hi Jon,

I have addressed your previous points, as well a having Jonathon from Sheffield having a review/look at the document. Jennifer and Ray addressed some of his concerns, and collectively we're happy for the document to be published.

Hopefully it meets with your approval now so I can publish.

Thanks,

Tom
