### ISSUE TITLE
Approval to publish: Patching

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#24]
Hello,

The Patching material is ready for publishing.

The original material is here:

- [https://intranet.justice.gov.uk/guidance/security/it-computer-security/ict-security-policy-framework/patch-management-standard/](https://intranet.justice.gov.uk/guidance/security/it-computer-security/ict-security-policy-framework/patch-management-standard/)

You can preview the revised version here:

- [https://github.com/ministryofjustice/itpolicycontent/blob/patching/content/confluence/enterprise/patch-management-standard.md](https://github.com/ministryofjustice/itpolicycontent/blob/patching/content/confluence/enterprise/patch-management-standard.md)

Please may I request approval to publish?

Many thanks,

Adrian

**Comment by cybersquirrel** [comment]
I would suggest two small tweaks:

- Make it clear that the times in this are maximums not targets, and we may require certain systems to have a more aggressive patching approach.
- Slightly downplay the alternative options aspect; the primary mitigation is regular and reliable application of security updates.

Otherwise, APPROVED! 👍

**Comment by warmanaMOJ** [comment]
Thank you. Updated accordingly, and published. Now live.
