### ISSUE TITLE
Discuss and potentially create material on why some traditionally 'secret' data does not need to be secret

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#25]
An example is a domain name or IP address. For most systems, most of the time, do these details really need to be secret? A suitable (strong) firewall or network defence should protect the system.

Arguably, you might want to keep the access details for some systems secure (for example a legacy system that cannot be maintained or patched, perhaps?) But these should be exception/edge cases.

Rather than saying 'all IP addresses and domain names must be secure', is it better to say that such details need not be secure unless one or more of conditions X, Y, or Z apply?

**Comment by cybersquirrel** [comment]
I think it's indicative of a bigger problem. There are only a small number of situations where IP addresses and domain names need to be protected, and that's where context makes the overall information sensitive in some way. That could be because they're in an internet-facing log file, and so potentially reveal a link between an individual and their use of our services; or it could be because of context, such as you mention above. 

Put more broadly, I think that IP addresses and domain names are examples of pieces of information that Digital and Technology are responsible for, and as such we are responsible for explaining the handling protections around each piece of information.

**Comment by cybersquirrel** [comment]
I like this - reads really well. 

Do you think we should also have an information protection guide for data within Digital and Technology which would be more of the 'policy' part of this (e.g. "IP addresses: not sensitive unless they relate to a citizen")?

**Comment by cybersquirrel** [comment]
Perfect - happy with that. Approved!
