### ISSUE TITLE
Add Password Guidance for User Facing Services

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#68]

**Comment by Jamie-Atkinson** [comment]
Could you add guidance about not using a single word from the dictionary/ preferably using a combination of uppercase, lowercase, numbers and specials for all users as a non System administrators or developers
may not scroll down to the part where this is stated?

**Comment by joelgsamuel** [comment]
Password length shouldn't be unlimited, capped to 4096 chars due to some DDoS considerations (forced to calc super long hash) from NCSC

**Comment by warmanaMOJ** [comment]
@cybersquirrel 

Please may I request approval to publish the updated password standard, based on a request to add information regarding User Facing Services?

I have added a new section, [here](https://github.com/ministryofjustice/itpolicycontent/blob/issue0068/content/security/framework/password-standard.md#user-facing-services) discussing UFSs.

I have also included direct feedback following review comments from discussion on `#security`, affecting the related document [password guidance](https://github.com/ministryofjustice/itpolicycontent/blob/issue0068/content/security/framework/password-guidance.md).

Thank you.

**Comment by cybersquirrel** [comment]
Hello,

Only comment is on the first bullet point in that section discussing UFSs, where it sort of sounds like it is the service's responsibility to ensure users have complex & different passwords, when I think our point is that we want to do nothing to discourage password management tools, so that they can have complex and different passwords for all of the services they use... maybe I'm overthinking this! 

Maybe tweak to "Password managers help people to have complex passwords which are different for each service they use, so we want to support their use"?

**Comment by warmanaMOJ** [comment]
Thank you - adjusted accordingly, and published.
